version: "3"

services: 
  kibana:
    networks: 
      - elk
    ports:
      - 5601:5601
    image: docker.elastic.co/kibana/kibana:6.4.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearchdb:9200
    labels: 
     - "fasibiotracking.enabled=true"
  elasticsearchdb: 
    image: elasticsearch:6.4.3
    ports: 
      - 127.0.0.1:9200:9200
      - 9300:9300
    networks: 
      - elk
    environment: 
      - discovery.type=single-node
    labels: 
     - "fasibiotracking.enabled=true"
networks:
  elk:
    external: true