version: "3"

services: 
  grafana: 
    networks: 
      - elk
    labels: 
      "funk.searchindex": "kibana"
    image: grafana/grafana
    ports: 
     - 3123:3000
    environment: 
      GF_SECURITY_ADMIN_PASSWORD: secret
  kibana:
    networks: 
      - elk
    labels: 
      "funk.log.staticcontent": "{\"kibanaspezialv\": 1}"
      "funk.searchindex": "kibana"
    ports:
      - 5601:5601
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      # ELASTICSEARCH_USERNAME: elastic
      # ELASTICSEARCH_PASSWORD: MagicWord
  elasticsearch: 
    image: elasticsearch:7.2.0
    labels: 
      "funk.log.staticcontent": "{\"esspezialv\": 1}"
      "funk.searchindex": "elasticsearch"
    ports: 
      - 127.0.0.1:9200:9200
      - 9300:9300
    networks: 
      - elk
    environment: 
      # xpack.security.enabled: "true"
      # xpack.ml.enabled: "true"
      # xpack.watcher.enabled: "true"
      # ELASTIC_USERNAME: elastic
      # ELASTIC_PASSWORD: MagicWord
      discovery.type: single-node
networks:
  elk:
    external: true